# Generated by Django 3.1.5 on 2021-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointfeature',
            name='lastview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointfeature',
            name='zoom',
            field=models.FloatField(default=5),
        ),
    ]
