# Generated by Django 3.1.5 on 2021-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210122_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointfeature',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
